### ISSUE TITLE
Changes are not reliably fetched from the backend

### ISSUE THREAD

**Issue by daniellienert** [punktDe/editconflictprevention#1]
Steps to reproduce: 
1. Change exists for a node in another workspace
2. Navigate to that node with another user
 -> The red bar is shown denoting that there are changed
4. Klick on the red bar
 -> `nodeHasChangesAction` is called and returns true
 -> `getChangedNodesAction` is not called
 -> List is empty (or shows the changes when the modal was last opened)
5. reload the host frame
6. klick on the bar
-> Correct data is shown

**Comment by c4ll-m3-j4ck** [comment]
This seems to be an issue with the lifecycle-methods of the react components. I'll look into it and see if I can figure out how to  make sure, the components check for the correct content every time it is required.
