### ISSUE TITLE
Allow further edits in private/internal workspaces

### ISSUE THREAD

**Issue by jobee** [punktDe/editconflictprevention#8]
The feature this package provides works great with no additional private or internal workspaces in place.

Editing workflows:
* User workspace => Internal workspace => Live workspace
* User workspace => Private workspace => Live workspace

Editors publish changes to additional workspaces frequently to share them with the team before publishing to Live. Such workflow is pretty common, I guess. Editing a page in private/internal workspaces twice before publishing to Live is currently not possible (without granting the privileges `EditNodeWithChangesInOtherWorkspaces` and `EditNodePropertiesWithChangesInOtherWorkspaces`).

I'd suggest the following defaults:
* Deny further edits when a change in a User workspace exists
* Allow edits on pages that already have changes in private/internal workspaces (only if the target workspace matches!) - maybe show an info or warning that there are changes "in progress" for that specific page

**Comment by daniellienert** [comment]
Hey @jobee, 

we just started using workspaces in the project we developed that package for and stumbled over the same issues. 

Additionally to the problems you described, you currently cannot publish workspace to live if you are not an administrator.

Sadly, I did not find a way to prevent changes to workspaces only if the target does not match, as the privilege matcher does not know which target is selected. I guess A good way would be to show changes to internal / private workspaces as warning in the UI and don't prevent further editing.
